#!/usr/bin/php
<?php

function calc($u, $o, $qi) {
	return ((1 / ($o * sqrt(2 * M_PI))) * exp(-(pow($qi - $u, 2) / (2 * pow($o, 2)))));
}

function gauss($argv) {
	$u = floatval($argv[0]);
	$o = floatval($argv[1]);
	$p = 0.0;
	$result = 0;
	for ($i = 0.0; $i <= 200; $i+= 1) {
		echo $i . " " . number_format(calc($u, $o, $i) * 100, 2). "\n";
	}
}

function minQI($argv) {
	$u = floatval($argv[0]);
	$o = floatval($argv[1]);
	$q1 = floatval($argv[2]);
	$res = 0.0;
	for ($i = 0; $i <= $q1; $i+=0.01)
		$res += calc($u, $o, $i);
	echo number_format($res, 1) . "% of people have a IQ inferior to " . $q1 . "\n";
}

function betweenQI($argv) {
	$u = floatval($argv[0]);
	$o = floatval($argv[1]);
	$q1 = floatval($argv[2]);
	$q2 = floatval($argv[3]);
	$res = 0.0;
	for ($i = $q1; $i <= $q2; $i+= 0.01)
		$res += calc($u, $o, $i);
	echo number_format($res, 1) . "% of people have a IQ between " . $q1 . " and " . $q2 . "\n";	
}

function error($argv) {
	if (count($argv) < 2 || count($argv) > 4){
		echo "usage: ./205IQ u o [IQ1] [IQ2]\n";
		exit(84);
	}
	for ($i = 0; $i < count($argv); $i++) {
		if (!is_numeric($argv[$i])) {
			echo "Arguments have to be numbers\n";
			exit(84);
		}
	}
	if (count($argv) == 4) {
		if (floatval($argv[2]) > floatval($argv[3])) {
			echo "First IQ must be inferior to the second one\n";
			exit(84);
		}
	}
	if (floatval($argv[0]) < 0 || floatval($argv[0]) > 200 || floatval($argv[1]) < 0 || floatval($argv[1]) > 200) {
		echo "First two arguments have to be numbers between 0 and 200\n";
		exit(84);
	}
}

array_shift($argv);
error($argv);
if (count($argv) == 2) {
	gauss($argv);
}
if (count($argv) == 3) {
	minQI($argv);
}
if (count($argv) == 4) {
	betweenQI($argv);
}